module.exports = {
	// development | production
	MODE: 'development',
	// compress CSS & Js files?
	COMPRESSION: true,
	// ['blocks']
	SUPPORTS: {{pluginSupports}},
	browserSyncOptions: {
		// localhost url to proxy
		port: 10018,
		notify: true,
		ui: false,
		proxy: {
			target: '{{proxy}}',
		},
	},
	watchFiles: {
		php: false,
		scss: true,
		js: true,
		images: true,
	},
	PATHS: {
		root: './',
		src: './src',
		js: './src/assets/js',
		scss: './src/assets/scss',
		images: './src/assets/img',
		fonts: './src/assets/fonts',
		dist: './dist',
		devdist: './dev-dist',
		node: './node_modules/',
		outputcss: './assets/css',
		outputjs: './assets/js',
		outputimg: './assets/img',
		outputfonts: './assets/fonts',
		blocks: './src/blocks',
		outputblocks: './blocks',
	},
	distIgnore: [
		'.*',
		'.**/*',
		'./node_modules/**',
		'./src/**',
		'./assets/**/maps/**',
		'./assets/**/maps/**/*.map',
		'readme.md',
		'package.json',
		'package-lock.json',
		'CHANGELOG.md',
		'./gulpfile.js/**',
		'composer.*',
		'LICENSE',
		'./.vscode/**',
		'./dist/**',
		'./dev-dist/**',
		'.husky/**',
		'webpack.config.js',
		'todo',
		'./wordpress/',
		'./php-stubs/',
		'./phpunit.xml.dist',
		'./tests/**/**',
		'./docker-configs/',
		'docker-compose.yaml',
	],
	devDistIgnore: [
		'./node_modules/**',
		'./vendor/**',
		'./dist/**',
		'./dev-dist/**',
		'./.git/**',
	],
};
