version: '3.1'

services:

  wordpress:
    build:
      context: .
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user1
      WORDPRESS_DB_PASSWORD: pass1
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/stacker-boilerplate
    networks:
      stacker-plugin:


  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass1
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      stacker-plugin:


  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      stacker-plugin:


  mailcatcher:
    image: dockage/mailcatcher
    restart: always
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      stacker-plugin:


volumes:
  wordpress:
  db:
  db2:


networks:
  stacker-plugin:
